// Exercise Library for Workout Generation
// Each exercise includes: name, category, muscle groups, duration, sets/reps, difficulty, and health restriction flags

export interface Exercise {
  id: string
  name: string
  category: 'strength' | 'cardio' | 'hiit' | 'flexibility' | 'compound'
  muscleGroups: string[]
  defaultSets?: number
  defaultReps?: string // "12" or "30 sec" for timed exercises
  durationMinutes: number // estimated time for this exercise
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  equipment: string[] // empty = bodyweight
  // Health restriction flags — if true, AVOID for users with this restriction
  contraindications: {
    back_injury?: boolean
    knee_injury?: boolean
    shoulder_injury?: boolean
    heart_condition?: boolean
    recent_surgery?: boolean
    asthma?: boolean
    wrist_injury?: boolean
    hip_injury?: boolean
  }
}

export const exerciseLibrary: Record<string, Exercise[]> = {
  // =============================================
  // 💪 BUILD MUSCLE — Strength & Hypertrophy
  // =============================================
  build_muscle: [
    // Upper Body Push
    {
      id: 'bm_01',
      name: 'Barbell Bench Press',
      category: 'strength',
      muscleGroups: ['chest', 'triceps', 'shoulders'],
      defaultSets: 4,
      defaultReps: '8-10',
      durationMinutes: 8,
      difficulty: 'intermediate',
      equipment: ['barbell', 'bench'],
      contraindications: { shoulder_injury: true, recent_surgery: true },
    },
    {
      id: 'bm_02',
      name: 'Dumbbell Shoulder Press',
      category: 'strength',
      muscleGroups: ['shoulders', 'triceps'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 6,
      difficulty: 'intermediate',
      equipment: ['dumbbells'],
      contraindications: { shoulder_injury: true },
    },
    {
      id: 'bm_03',
      name: 'Push-Ups',
      category: 'strength',
      muscleGroups: ['chest', 'triceps', 'core'],
      defaultSets: 3,
      defaultReps: '12-15',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { wrist_injury: true, shoulder_injury: true },
    },
    {
      id: 'bm_04',
      name: 'Incline Dumbbell Press',
      category: 'strength',
      muscleGroups: ['upper chest', 'shoulders', 'triceps'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 7,
      difficulty: 'intermediate',
      equipment: ['dumbbells', 'incline bench'],
      contraindications: { shoulder_injury: true },
    },
    {
      id: 'bm_05',
      name: 'Tricep Dips',
      category: 'strength',
      muscleGroups: ['triceps', 'chest', 'shoulders'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 5,
      difficulty: 'intermediate',
      equipment: ['dip bars'],
      contraindications: { shoulder_injury: true, wrist_injury: true },
    },

    // Upper Body Pull
    {
      id: 'bm_06',
      name: 'Barbell Rows',
      category: 'strength',
      muscleGroups: ['back', 'biceps'],
      defaultSets: 4,
      defaultReps: '8-10',
      durationMinutes: 7,
      difficulty: 'intermediate',
      equipment: ['barbell'],
      contraindications: { back_injury: true },
    },
    {
      id: 'bm_07',
      name: 'Pull-Ups',
      category: 'strength',
      muscleGroups: ['back', 'biceps', 'core'],
      defaultSets: 3,
      defaultReps: '6-10',
      durationMinutes: 6,
      difficulty: 'advanced',
      equipment: ['pull-up bar'],
      contraindications: { shoulder_injury: true },
    },
    {
      id: 'bm_08',
      name: 'Dumbbell Bicep Curls',
      category: 'strength',
      muscleGroups: ['biceps'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: ['dumbbells'],
      contraindications: { wrist_injury: true },
    },
    {
      id: 'bm_09',
      name: 'Lat Pulldown',
      category: 'strength',
      muscleGroups: ['back', 'biceps'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 6,
      difficulty: 'beginner',
      equipment: ['cable machine'],
      contraindications: { shoulder_injury: true },
    },
    {
      id: 'bm_10',
      name: 'Face Pulls',
      category: 'strength',
      muscleGroups: ['rear delts', 'upper back'],
      defaultSets: 3,
      defaultReps: '12-15',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: ['cable machine'],
      contraindications: { shoulder_injury: true },
    },

    // Lower Body
    {
      id: 'bm_11',
      name: 'Barbell Squats',
      category: 'compound',
      muscleGroups: ['quads', 'glutes', 'hamstrings', 'core'],
      defaultSets: 4,
      defaultReps: '8-10',
      durationMinutes: 10,
      difficulty: 'intermediate',
      equipment: ['barbell', 'squat rack'],
      contraindications: { knee_injury: true, back_injury: true },
    },
    {
      id: 'bm_12',
      name: 'Romanian Deadlift',
      category: 'compound',
      muscleGroups: ['hamstrings', 'glutes', 'lower back'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 8,
      difficulty: 'intermediate',
      equipment: ['barbell'],
      contraindications: { back_injury: true },
    },
    {
      id: 'bm_13',
      name: 'Leg Press',
      category: 'strength',
      muscleGroups: ['quads', 'glutes'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 7,
      difficulty: 'beginner',
      equipment: ['leg press machine'],
      contraindications: { knee_injury: true },
    },
    {
      id: 'bm_14',
      name: 'Walking Lunges',
      category: 'strength',
      muscleGroups: ['quads', 'glutes', 'hamstrings'],
      defaultSets: 3,
      defaultReps: '12 each leg',
      durationMinutes: 7,
      difficulty: 'intermediate',
      equipment: ['dumbbells'],
      contraindications: { knee_injury: true },
    },
    {
      id: 'bm_15',
      name: 'Calf Raises',
      category: 'strength',
      muscleGroups: ['calves'],
      defaultSets: 4,
      defaultReps: '15-20',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
  ],

  // =============================================
  // 🔥 LOSE WEIGHT — Fat Burn & Calorie Deficit
  // =============================================
  lose_weight: [
    {
      id: 'lw_01',
      name: 'Jump Rope',
      category: 'cardio',
      muscleGroups: ['full body', 'calves', 'shoulders'],
      defaultSets: 3,
      defaultReps: '60 sec',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: ['jump rope'],
      contraindications: { knee_injury: true, heart_condition: true },
    },
    {
      id: 'lw_02',
      name: 'Burpees',
      category: 'hiit',
      muscleGroups: ['full body'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 5,
      difficulty: 'intermediate',
      equipment: [],
      contraindications: {
        knee_injury: true,
        back_injury: true,
        heart_condition: true,
        wrist_injury: true,
      },
    },
    {
      id: 'lw_03',
      name: 'Mountain Climbers',
      category: 'hiit',
      muscleGroups: ['core', 'shoulders', 'quads'],
      defaultSets: 3,
      defaultReps: '30 sec',
      durationMinutes: 4,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { wrist_injury: true, shoulder_injury: true },
    },
    {
      id: 'lw_04',
      name: 'Kettlebell Swings',
      category: 'hiit',
      muscleGroups: ['glutes', 'hamstrings', 'core', 'shoulders'],
      defaultSets: 3,
      defaultReps: '15-20',
      durationMinutes: 6,
      difficulty: 'intermediate',
      equipment: ['kettlebell'],
      contraindications: { back_injury: true, shoulder_injury: true },
    },
    {
      id: 'lw_05',
      name: 'Treadmill Intervals',
      category: 'cardio',
      muscleGroups: ['legs', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '20 min',
      durationMinutes: 20,
      difficulty: 'beginner',
      equipment: ['treadmill'],
      contraindications: { knee_injury: true, heart_condition: true, asthma: true },
    },
    {
      id: 'lw_06',
      name: 'Cycling / Spin',
      category: 'cardio',
      muscleGroups: ['quads', 'hamstrings', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '25 min',
      durationMinutes: 25,
      difficulty: 'beginner',
      equipment: ['stationary bike'],
      contraindications: { knee_injury: true, heart_condition: true },
    },
    {
      id: 'lw_07',
      name: 'Box Jumps',
      category: 'hiit',
      muscleGroups: ['quads', 'glutes', 'calves'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 5,
      difficulty: 'intermediate',
      equipment: ['plyo box'],
      contraindications: { knee_injury: true, back_injury: true, heart_condition: true },
    },
    {
      id: 'lw_08',
      name: 'Battle Ropes',
      category: 'hiit',
      muscleGroups: ['arms', 'shoulders', 'core'],
      defaultSets: 3,
      defaultReps: '30 sec',
      durationMinutes: 5,
      difficulty: 'intermediate',
      equipment: ['battle ropes'],
      contraindications: { shoulder_injury: true, wrist_injury: true },
    },
    {
      id: 'lw_09',
      name: 'Rowing Machine',
      category: 'cardio',
      muscleGroups: ['back', 'legs', 'arms', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '15 min',
      durationMinutes: 15,
      difficulty: 'beginner',
      equipment: ['rowing machine'],
      contraindications: { back_injury: true, heart_condition: true },
    },
    {
      id: 'lw_10',
      name: 'High Knees',
      category: 'cardio',
      muscleGroups: ['quads', 'core', 'cardiovascular'],
      defaultSets: 3,
      defaultReps: '30 sec',
      durationMinutes: 4,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { knee_injury: true, heart_condition: true },
    },
    {
      id: 'lw_11',
      name: 'Squat Jumps',
      category: 'hiit',
      muscleGroups: ['quads', 'glutes', 'calves'],
      defaultSets: 3,
      defaultReps: '12-15',
      durationMinutes: 5,
      difficulty: 'intermediate',
      equipment: [],
      contraindications: { knee_injury: true, back_injury: true },
    },
    {
      id: 'lw_12',
      name: 'Walking (Brisk)',
      category: 'cardio',
      muscleGroups: ['legs', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '30 min',
      durationMinutes: 30,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
  ],

  // =============================================
  // 🏃 IMPROVE ENDURANCE — Stamina & Cardio
  // =============================================
  improve_endurance: [
    {
      id: 'ie_01',
      name: 'Steady-State Running',
      category: 'cardio',
      muscleGroups: ['legs', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '30 min',
      durationMinutes: 30,
      difficulty: 'intermediate',
      equipment: [],
      contraindications: { knee_injury: true, heart_condition: true, asthma: true },
    },
    {
      id: 'ie_02',
      name: 'Swimming Laps',
      category: 'cardio',
      muscleGroups: ['full body', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '25 min',
      durationMinutes: 25,
      difficulty: 'intermediate',
      equipment: ['pool'],
      contraindications: { recent_surgery: true },
    },
    {
      id: 'ie_03',
      name: 'Cycling Long Distance',
      category: 'cardio',
      muscleGroups: ['quads', 'hamstrings', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '40 min',
      durationMinutes: 40,
      difficulty: 'intermediate',
      equipment: ['bicycle'],
      contraindications: { knee_injury: true, heart_condition: true },
    },
    {
      id: 'ie_04',
      name: 'Stair Climbing',
      category: 'cardio',
      muscleGroups: ['quads', 'glutes', 'calves', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '15 min',
      durationMinutes: 15,
      difficulty: 'intermediate',
      equipment: ['stairs or stair machine'],
      contraindications: { knee_injury: true, heart_condition: true },
    },
    {
      id: 'ie_05',
      name: 'Elliptical Trainer',
      category: 'cardio',
      muscleGroups: ['full body', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '25 min',
      durationMinutes: 25,
      difficulty: 'beginner',
      equipment: ['elliptical'],
      contraindications: { heart_condition: true },
    },
    {
      id: 'ie_06',
      name: 'Jump Rope Endurance',
      category: 'cardio',
      muscleGroups: ['calves', 'shoulders', 'cardiovascular'],
      defaultSets: 5,
      defaultReps: '2 min on / 30 sec rest',
      durationMinutes: 15,
      difficulty: 'intermediate',
      equipment: ['jump rope'],
      contraindications: { knee_injury: true, heart_condition: true },
    },
    {
      id: 'ie_07',
      name: 'Rowing Intervals',
      category: 'cardio',
      muscleGroups: ['back', 'legs', 'arms', 'cardiovascular'],
      defaultSets: 6,
      defaultReps: '3 min on / 1 min rest',
      durationMinutes: 24,
      difficulty: 'intermediate',
      equipment: ['rowing machine'],
      contraindications: { back_injury: true, heart_condition: true },
    },
    {
      id: 'ie_08',
      name: 'Plank Hold',
      category: 'strength',
      muscleGroups: ['core', 'shoulders'],
      defaultSets: 3,
      defaultReps: '45-60 sec',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { shoulder_injury: true, wrist_injury: true },
    },
    {
      id: 'ie_09',
      name: 'Bodyweight Circuit',
      category: 'hiit',
      muscleGroups: ['full body'],
      defaultSets: 3,
      defaultReps: '10 each exercise',
      durationMinutes: 15,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { heart_condition: true },
    },
    {
      id: 'ie_10',
      name: 'Shadow Boxing',
      category: 'cardio',
      muscleGroups: ['arms', 'shoulders', 'core', 'cardiovascular'],
      defaultSets: 3,
      defaultReps: '3 min rounds',
      durationMinutes: 12,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { shoulder_injury: true },
    },
  ],

  // =============================================
  // 🧘 INCREASE FLEXIBILITY — Mobility & Stretch
  // =============================================
  increase_flexibility: [
    {
      id: 'if_01',
      name: 'Sun Salutations (Yoga)',
      category: 'flexibility',
      muscleGroups: ['full body'],
      defaultSets: 1,
      defaultReps: '10 rounds',
      durationMinutes: 15,
      difficulty: 'beginner',
      equipment: ['yoga mat'],
      contraindications: { wrist_injury: true },
    },
    {
      id: 'if_02',
      name: 'Hip Flexor Stretch',
      category: 'flexibility',
      muscleGroups: ['hip flexors', 'quads'],
      defaultSets: 2,
      defaultReps: '30 sec each side',
      durationMinutes: 3,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { knee_injury: true, hip_injury: true },
    },
    {
      id: 'if_03',
      name: 'Hamstring Stretch',
      category: 'flexibility',
      muscleGroups: ['hamstrings', 'lower back'],
      defaultSets: 2,
      defaultReps: '30 sec each leg',
      durationMinutes: 3,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { back_injury: true },
    },
    {
      id: 'if_04',
      name: 'Pigeon Pose',
      category: 'flexibility',
      muscleGroups: ['glutes', 'hip flexors'],
      defaultSets: 2,
      defaultReps: '45 sec each side',
      durationMinutes: 4,
      difficulty: 'intermediate',
      equipment: ['yoga mat'],
      contraindications: { knee_injury: true, hip_injury: true },
    },
    {
      id: 'if_05',
      name: "Child's Pose",
      category: 'flexibility',
      muscleGroups: ['back', 'shoulders', 'hips'],
      defaultSets: 1,
      defaultReps: '60 sec',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: ['yoga mat'],
      contraindications: { knee_injury: true },
    },
    {
      id: 'if_06',
      name: 'Cat-Cow Stretch',
      category: 'flexibility',
      muscleGroups: ['spine', 'core'],
      defaultSets: 1,
      defaultReps: '10 rounds',
      durationMinutes: 3,
      difficulty: 'beginner',
      equipment: ['yoga mat'],
      contraindications: { wrist_injury: true },
    },
    {
      id: 'if_07',
      name: 'Shoulder Stretch & Pass-Through',
      category: 'flexibility',
      muscleGroups: ['shoulders', 'chest'],
      defaultSets: 2,
      defaultReps: '10 reps',
      durationMinutes: 3,
      difficulty: 'beginner',
      equipment: ['resistance band or stick'],
      contraindications: { shoulder_injury: true },
    },
    {
      id: 'if_08',
      name: 'Seated Spinal Twist',
      category: 'flexibility',
      muscleGroups: ['spine', 'obliques', 'glutes'],
      defaultSets: 2,
      defaultReps: '30 sec each side',
      durationMinutes: 3,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { back_injury: true },
    },
    {
      id: 'if_09',
      name: 'Downward Dog',
      category: 'flexibility',
      muscleGroups: ['hamstrings', 'calves', 'shoulders', 'back'],
      defaultSets: 1,
      defaultReps: '45-60 sec',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: ['yoga mat'],
      contraindications: { wrist_injury: true, shoulder_injury: true },
    },
    {
      id: 'if_10',
      name: 'Foam Rolling (Full Body)',
      category: 'flexibility',
      muscleGroups: ['full body'],
      defaultSets: 1,
      defaultReps: '60 sec per muscle group',
      durationMinutes: 10,
      difficulty: 'beginner',
      equipment: ['foam roller'],
      contraindications: {},
    },
  ],

  // =============================================
  // ⭐ GENERAL FITNESS — Balanced & Well-Rounded
  // =============================================
  general_fitness: [
    {
      id: 'gf_01',
      name: 'Bodyweight Squats',
      category: 'strength',
      muscleGroups: ['quads', 'glutes'],
      defaultSets: 3,
      defaultReps: '15-20',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { knee_injury: true },
    },
    {
      id: 'gf_02',
      name: 'Push-Ups',
      category: 'strength',
      muscleGroups: ['chest', 'triceps', 'core'],
      defaultSets: 3,
      defaultReps: '10-15',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { wrist_injury: true, shoulder_injury: true },
    },
    {
      id: 'gf_03',
      name: 'Plank',
      category: 'strength',
      muscleGroups: ['core', 'shoulders'],
      defaultSets: 3,
      defaultReps: '30-45 sec',
      durationMinutes: 4,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { shoulder_injury: true, wrist_injury: true },
    },
    {
      id: 'gf_04',
      name: 'Dumbbell Lunges',
      category: 'strength',
      muscleGroups: ['quads', 'glutes', 'hamstrings'],
      defaultSets: 3,
      defaultReps: '10 each leg',
      durationMinutes: 6,
      difficulty: 'beginner',
      equipment: ['dumbbells'],
      contraindications: { knee_injury: true },
    },
    {
      id: 'gf_05',
      name: 'Brisk Walking / Light Jog',
      category: 'cardio',
      muscleGroups: ['legs', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '20 min',
      durationMinutes: 20,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
    {
      id: 'gf_06',
      name: 'Dumbbell Rows',
      category: 'strength',
      muscleGroups: ['back', 'biceps'],
      defaultSets: 3,
      defaultReps: '10-12',
      durationMinutes: 6,
      difficulty: 'beginner',
      equipment: ['dumbbells'],
      contraindications: { back_injury: true },
    },
    {
      id: 'gf_07',
      name: 'Jumping Jacks',
      category: 'cardio',
      muscleGroups: ['full body', 'cardiovascular'],
      defaultSets: 3,
      defaultReps: '30 sec',
      durationMinutes: 4,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { knee_injury: true, heart_condition: true },
    },
    {
      id: 'gf_08',
      name: 'Dead Bugs',
      category: 'strength',
      muscleGroups: ['core'],
      defaultSets: 3,
      defaultReps: '10 each side',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
    {
      id: 'gf_09',
      name: 'Glute Bridges',
      category: 'strength',
      muscleGroups: ['glutes', 'hamstrings', 'core'],
      defaultSets: 3,
      defaultReps: '12-15',
      durationMinutes: 5,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
    {
      id: 'gf_10',
      name: 'Standing Calf Raises',
      category: 'strength',
      muscleGroups: ['calves'],
      defaultSets: 3,
      defaultReps: '15-20',
      durationMinutes: 4,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
  ],

  // =============================================
  // 🔥 WARMUP EXERCISES — Used at start of every session
  // =============================================
  warmup: [
    {
      id: 'wu_01',
      name: 'Arm Circles',
      category: 'flexibility',
      muscleGroups: ['shoulders'],
      defaultSets: 1,
      defaultReps: '20 each direction',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { shoulder_injury: true },
    },
    {
      id: 'wu_02',
      name: 'Leg Swings',
      category: 'flexibility',
      muscleGroups: ['hip flexors', 'hamstrings'],
      defaultSets: 1,
      defaultReps: '15 each leg',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { hip_injury: true },
    },
    {
      id: 'wu_03',
      name: 'Jumping Jacks',
      category: 'cardio',
      muscleGroups: ['full body', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '30 sec',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { knee_injury: true, heart_condition: true },
    },
    {
      id: 'wu_04',
      name: 'Hip Circles',
      category: 'flexibility',
      muscleGroups: ['hips', 'glutes'],
      defaultSets: 1,
      defaultReps: '10 each direction',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { hip_injury: true },
    },
    {
      id: 'wu_05',
      name: 'High Knees (Light)',
      category: 'cardio',
      muscleGroups: ['quads', 'core', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '20 sec',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { knee_injury: true, heart_condition: true },
    },
    {
      id: 'wu_06',
      name: 'Bodyweight Good Mornings',
      category: 'flexibility',
      muscleGroups: ['hamstrings', 'lower back'],
      defaultSets: 1,
      defaultReps: '10 reps',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { back_injury: true },
    },
    {
      id: 'wu_07',
      name: 'Torso Twists',
      category: 'flexibility',
      muscleGroups: ['obliques', 'spine'],
      defaultSets: 1,
      defaultReps: '10 each side',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { back_injury: true },
    },
    {
      id: 'wu_08',
      name: 'Neck Rolls',
      category: 'flexibility',
      muscleGroups: ['neck'],
      defaultSets: 1,
      defaultReps: '5 each direction',
      durationMinutes: 1,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
    {
      id: 'wu_09',
      name: 'Butt Kicks',
      category: 'cardio',
      muscleGroups: ['hamstrings', 'cardiovascular'],
      defaultSets: 1,
      defaultReps: '20 sec',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { knee_injury: true },
    },
    {
      id: 'wu_10',
      name: 'Wrist Circles',
      category: 'flexibility',
      muscleGroups: ['wrists', 'forearms'],
      defaultSets: 1,
      defaultReps: '10 each direction',
      durationMinutes: 1,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
  ],

  // =============================================
  // 🧊 COOLDOWN EXERCISES — Used at end of every session
  // =============================================
  cooldown: [
    {
      id: 'cd_01',
      name: 'Standing Quad Stretch',
      category: 'flexibility',
      muscleGroups: ['quads'],
      defaultSets: 1,
      defaultReps: '30 sec each leg',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { knee_injury: true },
    },
    {
      id: 'cd_02',
      name: 'Standing Hamstring Stretch',
      category: 'flexibility',
      muscleGroups: ['hamstrings'],
      defaultSets: 1,
      defaultReps: '30 sec each leg',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
    {
      id: 'cd_03',
      name: 'Chest Doorway Stretch',
      category: 'flexibility',
      muscleGroups: ['chest', 'shoulders'],
      defaultSets: 1,
      defaultReps: '30 sec',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { shoulder_injury: true },
    },
    {
      id: 'cd_04',
      name: 'Seated Forward Fold',
      category: 'flexibility',
      muscleGroups: ['hamstrings', 'lower back'],
      defaultSets: 1,
      defaultReps: '45 sec',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { back_injury: true },
    },
    {
      id: 'cd_05',
      name: "Child's Pose",
      category: 'flexibility',
      muscleGroups: ['back', 'shoulders', 'hips'],
      defaultSets: 1,
      defaultReps: '45 sec',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { knee_injury: true },
    },
    {
      id: 'cd_06',
      name: 'Cross-Body Shoulder Stretch',
      category: 'flexibility',
      muscleGroups: ['shoulders', 'upper back'],
      defaultSets: 1,
      defaultReps: '30 sec each arm',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { shoulder_injury: true },
    },
    {
      id: 'cd_07',
      name: 'Lying Spinal Twist',
      category: 'flexibility',
      muscleGroups: ['spine', 'glutes', 'obliques'],
      defaultSets: 1,
      defaultReps: '30 sec each side',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { back_injury: true },
    },
    {
      id: 'cd_08',
      name: 'Deep Breathing',
      category: 'flexibility',
      muscleGroups: ['diaphragm'],
      defaultSets: 1,
      defaultReps: '10 deep breaths',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
    {
      id: 'cd_09',
      name: 'Figure-4 Glute Stretch',
      category: 'flexibility',
      muscleGroups: ['glutes', 'hips'],
      defaultSets: 1,
      defaultReps: '30 sec each side',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: { hip_injury: true, knee_injury: true },
    },
    {
      id: 'cd_10',
      name: 'Calf Stretch (Wall)',
      category: 'flexibility',
      muscleGroups: ['calves'],
      defaultSets: 1,
      defaultReps: '30 sec each leg',
      durationMinutes: 2,
      difficulty: 'beginner',
      equipment: [],
      contraindications: {},
    },
  ],
}

// =============================================
// WORKOUT SESSION TEMPLATES
// Used to structure "Today's Workout Session"
// =============================================
export interface WorkoutSession {
  name: string
  description: string
  targetDuration: number // minutes
  warmup: Exercise[]
  mainExercises: Exercise[]
  cooldown: Exercise[]
}

// Session structure templates by goal
export const sessionTemplates: Record<
  string,
  { name: string; focus: string[]; exerciseCount: number; duration: number }[]
> = {
  build_muscle: [
    {
      name: 'Upper Body Push Day',
      focus: ['chest', 'shoulders', 'triceps'],
      exerciseCount: 5,
      duration: 45,
    },
    { name: 'Upper Body Pull Day', focus: ['back', 'biceps'], exerciseCount: 5, duration: 45 },
    {
      name: 'Leg Day',
      focus: ['quads', 'hamstrings', 'glutes', 'calves'],
      exerciseCount: 5,
      duration: 50,
    },
    { name: 'Full Body Strength', focus: ['full body'], exerciseCount: 6, duration: 55 },
    { name: 'Arms & Core', focus: ['biceps', 'triceps', 'core'], exerciseCount: 5, duration: 40 },
  ],
  lose_weight: [
    { name: 'HIIT Fat Burner', focus: ['full body'], exerciseCount: 6, duration: 30 },
    { name: 'Cardio Blast', focus: ['cardiovascular'], exerciseCount: 4, duration: 35 },
    { name: 'Metabolic Circuit', focus: ['full body'], exerciseCount: 6, duration: 25 },
    { name: 'Low Impact Burn', focus: ['full body'], exerciseCount: 5, duration: 40 },
    { name: 'Tabata Style', focus: ['full body'], exerciseCount: 8, duration: 20 },
  ],
  improve_endurance: [
    { name: 'Steady State Cardio', focus: ['cardiovascular'], exerciseCount: 3, duration: 40 },
    {
      name: 'Interval Training',
      focus: ['cardiovascular', 'legs'],
      exerciseCount: 4,
      duration: 35,
    },
    { name: 'Endurance Circuit', focus: ['full body'], exerciseCount: 5, duration: 45 },
    {
      name: 'Core & Cardio Combo',
      focus: ['core', 'cardiovascular'],
      exerciseCount: 5,
      duration: 30,
    },
    {
      name: 'Active Recovery Run',
      focus: ['legs', 'cardiovascular'],
      exerciseCount: 3,
      duration: 30,
    },
  ],
  increase_flexibility: [
    { name: 'Morning Yoga Flow', focus: ['full body'], exerciseCount: 8, duration: 30 },
    { name: 'Deep Stretch Session', focus: ['full body'], exerciseCount: 8, duration: 25 },
    { name: 'Hip & Back Release', focus: ['hips', 'back'], exerciseCount: 6, duration: 20 },
    {
      name: 'Upper Body Mobility',
      focus: ['shoulders', 'chest', 'spine'],
      exerciseCount: 6,
      duration: 20,
    },
    { name: 'Recovery & Foam Roll', focus: ['full body'], exerciseCount: 5, duration: 25 },
  ],
  general_fitness: [
    { name: 'Full Body Workout', focus: ['full body'], exerciseCount: 6, duration: 40 },
    { name: 'Strength & Cardio Mix', focus: ['full body'], exerciseCount: 6, duration: 35 },
    { name: 'Core Focus Day', focus: ['core', 'full body'], exerciseCount: 5, duration: 30 },
    { name: 'Active Day', focus: ['legs', 'cardiovascular'], exerciseCount: 5, duration: 35 },
    { name: 'Light & Easy', focus: ['full body'], exerciseCount: 4, duration: 25 },
  ],
}
